theme: jekyll-theme-slate # https://github.com/pages-themes/slate
title: Table-Top Game Equipment
description: a.k.a. TaToGE
show_downloads: true
github:
  zip_url: https://github.com/quasart/TaToGE/releases/latest
  owner_name: Alfred Massard
